[package]
name = "clober_cairo"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.6.3"
authors = ["Clober <dev@clober.io>"]
description = "Core Contracts written in Cairo for StarkNet"
readme = "README.md"
repository = "https://github.com/clober-dex/clober_cairo"
# license-file = "LICENSE"

[dependencies]
starknet = "2.6.3"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.24.0" }

[scripts]   
test = "snforge test"
