name: Lint and test

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  lint_and_test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract scarb version
      run: |
        SCARB_VERSION=$(grep 'cairo-version = ' Scarb.toml | sed 's/cairo-version = "\(.*\)"/\1/')
        echo "SCARB_VERSION=$SCARB_VERSION" >> $GITHUB_ENV
    - uses: software-mansion/setup-scarb@v1
      with:
        scarb-version: ${{ env.SCARB_VERSION }}
    - name: Cairo lint
      run: scarb fmt --check
    - uses: foundry-rs/setup-snfoundry@v3
    - name: Cairo test
      run: scarb test
